import type { StoredSession } from "../src/shared/types";
import { resolveExtensionConfig } from "../src/shared/config";

export function createStoredSession(
  overrides: Partial<StoredSession> = {},
): StoredSession {
  const config = resolveExtensionConfig({
    applicationName: "Demo application",
    environment: "test",
    metadata: { testCaseId: "TC-101" },
    preferences: {
      captureVideo: false,
      includeAudio: false,
      automaticScreenshots: false,
      captureRequestBody: false,
      captureResponseBody: false,
      maxVideoDurationMinutes: 30,
      maskSelectors: ["[data-sensitive]"],
      excludeSelectors: [],
      sensitiveQueryParameters: [],
    },
  });
  const startedAt = "2026-09-26T12:00:00.000Z";
  return {
    schemaVersion: 1,
    revision: 1,
    sessionId: "tw-session-1",
    phase: "recording",
    result: "not-set",
    targetTabId: 11,
    targetWindowId: 22,
    targetOrigin: "https://example.test",
    leaseId: "lease-1",
    pageAccess: "ready",
    metadata: {
      sessionId: "tw-session-1",
      applicationName: "Demo application",
      environment: "test",
      testCaseId: "TC-101",
      startedAt,
      durationMs: 0,
      currentUrl: "https://example.test/dashboard",
      pageTitle: "Dashboard",
      browser: { name: "Chrome", version: "140" },
      operatingSystem: { name: "macOS", version: "15" },
      viewport: { width: 1280, height: 720 },
      screen: { width: 1920, height: 1080 },
      libraryVersion: "@testwitness/extension-standard/0.1.0",
      result: "not-set",
      custom: {},
    },
    config,
    preferences: {
      captureVideo: false,
      includeAudio: false,
      automaticScreenshots: false,
      captureRequestBody: false,
      captureResponseBody: false,
      maxVideoDurationMinutes: 30,
      maskSelectors: ["[data-sensitive]"],
      excludeSelectors: [],
      sensitiveQueryParameters: [],
    },
    counts: {
      screenshots: 0,
      actions: 0,
      consoleLogs: 0,
      networkRequests: 0,
      successfulRequests: 0,
      networkErrors: 0,
      notes: 0,
      hasVideo: false,
    },
    approximateSizeBytes: 1_000,
    evidenceOrdinal: 0,
    actionSequence: 0,
    screenshotSequence: 0,
    videoStatus: "off",
    warnings: [],
    createdAt: startedAt,
    updatedAt: startedAt,
    ...overrides,
  };
}
